<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = [
            // Caloocan City University with multiple campuses
            [
                'name' => 'Caloocan City University',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-1234-5678',
                'email' => 'info@ccu.edu.ph',
                'website' => 'www.ccu.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City University',
                'campus' => 'South Campus',
                'contact_number' => '+63-2-1234-5679',
                'email' => 'south@ccu.edu.ph',
                'website' => 'www.ccu.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City University',
                'campus' => 'North Campus',
                'contact_number' => '+63-2-1234-5680',
                'email' => 'north@ccu.edu.ph',
                'website' => 'www.ccu.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City Science High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-2345-6789',
                'email' => 'info@ccshs.edu.ph',
                'website' => 'www.ccshs.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'St. Gabriel Academy',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-3456-7890',
                'email' => 'info@stgabriel.edu.ph',
                'website' => 'www.stgabriel.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'St. Gabriel Academy',
                'campus' => 'Extension Campus',
                'contact_number' => '+63-2-3456-7891',
                'email' => 'extension@stgabriel.edu.ph',
                'website' => 'www.stgabriel.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan City Business High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-4567-8901',
                'email' => 'info@ccbhs.edu.ph',
                'website' => 'www.ccbhs.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Caloocan International Science and Technology High School',
                'campus' => 'Main Campus',
                'contact_number' => '+63-2-5678-9012',
                'email' => 'info@cisths.edu.ph',
                'website' => 'www.cisths.edu.ph',
                'classification' => 'STATE UNIVERSITY/COLLEGE (SUC)',
                'address' => 'Caloocan City',
                'city' => 'Caloocan',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1400',
                'is_public' => true,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Far Eastern University',
                'campus' => 'Nicanor Reyes Street',
                'contact_number' => '+63-2-8849-4000',
                'email' => 'info@feu.edu.ph',
                'website' => 'https://www.feu.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Nicanor Reyes Street, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1015',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Mapúa University',
                'campus' => 'Intramuros',
                'contact_number' => '+63-2-8247-5000',
                'email' => 'info@mapua.edu.ph',
                'website' => 'https://www.mapua.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => 'Muralla Street, Intramuros',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1002',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Adamson University',
                'campus' => 'San Marcelino',
                'contact_number' => '+63-2-8524-2011',
                'email' => 'info@adamson.edu.ph',
                'website' => 'https://www.adamson.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '900 San Marcelino Street, Ermita',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1000',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'National University',
                'campus' => 'Sampaloc',
                'contact_number' => '+63-2-8712-0000',
                'email' => 'info@national-u.edu.ph',
                'website' => 'https://www.national-u.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '551 M.F. Jhocson Street, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1015',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of the East',
                'campus' => 'Recto',
                'contact_number' => '+63-2-8735-5471',
                'email' => 'info@ue.edu.ph',
                'website' => 'https://www.ue.edu.ph',
                'classification' => 'PRIVATE UNIVERSITY/COLLEGE',
                'address' => '2219 C.M. Recto Avenue, Sampaloc',
                'city' => 'Manila',
                'province' => 'Metro Manila',
                'region' => 'NCR',
                'zip_code' => '1008',
                'is_public' => false,
                'is_partner_school' => true,
                'is_active' => true,
            ],
        ];

        foreach ($schools as $schoolData) {
            School::create($schoolData);
        }
    }
}
